server:
  port: ${SPRING_PORT}
  address: ${SPRING_HOST}

spring:
  # Setup database connection
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # Setup hibernate
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
  # Configure exceptions and disable automatic mapping of resources
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: '/metrics'
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

springfox:
  # Configure swagger to listen on /swagger-docs instead of /v2/api-docs
  documentation:
    swagger:
      v2:
        path: '/swagger-docs'